name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   
  workflow_dispatch:       

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: wiqilee
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_limit: 6
