name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"     
  workflow_dispatch:         

permissions:
  contents: write            

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Auth
          token: ${{ secrets.METRICS_TOKEN }}

          # Output
          filename: github-metrics.svg
          committer_branch: main
          committer_message: "chore: update github-metrics.svg"

          # Profil
          user: wiqilee
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta

          # Plugins ringan (aman untuk tes awal)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
